### ISSUE TITLE
get cell ID for each node

### ISSUE THREAD

**Issue by lijiacd985** [GregorySchwartz/birch-beer#1]
Hi Gregory Schwartz,

Is there possible to get the cell IDs for each node using birch-beer?

Step 1. using your hierarchical-spectral-clustering method to generate tree JSON file. 

The input is three column file represent the distance between two cells;
The "item" column is the cell IDs in label.csv file.

Step 2. Use JSON file as input for birch-beer.
Can I also get a file include each cell ID and corresponding node number?

Thanks,

Best,

Jia Li

**Comment by GregorySchwartz** [comment]
Do you mean getting cell ID per node using TooManyCells (the `node_info.csv` file)? If you are using BirchBeer then you already have the structure. TooManyCells has the functionality that you are looking for (the hierarchical clustering to BirchBeer). They are separate just in case you need them for independent reasons (another tree structure for BirchBeer) or just the clustering.

**Comment by lijiacd985** [comment]
I am planning to only use your hierarchical clustering to BirchBeer (NOT use too-many-cells) in a customized way.

In the above situation, is there possible to get cell ID (item column in labels.csv) for each node?

Thanks

**Comment by GregorySchwartz** [comment]
Per f94d182dda72f1fed7740222b05c0724d9f4545b, you can now use `--csv-output` in `birch-beer` to output the node path to the item.

**Comment by lijiacd985** [comment]
thanks.

I tried to use “docker pull gregoryschwartz/birch-beer:0.2.3.0” to install the updated one.

But, Error response from daemon: manifest for gregoryschwartz/birch-beer:0.2.3.0 not found: manifest unknown: manifest unknown.

I can only use Docker to install.

Thanks,

Best,

Jia li

**Comment by GregorySchwartz** [comment]
I pushed the new version to docker.
