### ISSUE TITLE
Birch-beer output

### ISSUE THREAD

**Issue by fabotao** [GregorySchwartz/birch-beer#2]
Hi, I am wondering when using the "birch-beer --input tree.json --labels-file labels.csv" command line. How do I get the final tree plot? As the workstation dose not have screen, so the image file is necessary. Thanks for your reply!

**Comment by GregorySchwartz** [comment]
There is an output argument you can specify, and I believe the default is `out`. So you should have an `out` folder in the directory that you ran `birch-beer`.

**Comment by fabotao** [comment]
Thanks very much. I have found that as your suggestion. 
Have a nice day!
Botao Fa----- 原始邮件 -----
发件人：Gregory Schwartz ***@***.***>
收件人：GregorySchwartz/birch-beer ***@***.***>
抄送人：fabotao ***@***.***>,  Author ***@***.***>
主题：Re: [GregorySchwartz/birch-beer] Birch-beer output (Issue #2)
日期：2022年05月14日 04点15分


There is an output argument you can specify, and I believe the default is out. So you should have an out folder in the directory that you ran birch-beer.
